/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsg.view;
import bsg.koneksi.UserSession;
import javax.swing.JFrame;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author kevadamargalih
 */
public class FrameMENU extends javax.swing.JFrame {
private static String levelUser;

JasperReport jasRep;
JasperPrint jasPrint;
JasperDesign jasDes;
Map param = new HashMap();
    /**
     * Creates new form FrameLOGIN
     */
    public FrameMENU() {
        initComponents();
        if(UserSession.getU_levelUser() == null){
            loginGagal();
            System.out.print("kosong");
        } else {
            smLogin.setText("Logout");
        }
        mnUser.setText(UserSession.getU_username());
        levelUser = UserSession.getU_levelUser();
        
    }
public static void loginGagal (){
    mnNilai.setVisible(false);
    mnJurusan.setVisible(false);
    mnMatkul.setVisible(false);
    mnUser.setVisible(false);
    mnMahasiswa.setVisible(false);
    smLogin.setText("Login");
}
public static void loginSukses () {
    mnNilai.setVisible(true);
    mnJurusan.setVisible(true);
    mnMatkul.setVisible(true);
    mnMahasiswa.setVisible(true);
    mnUser.setVisible(true);
    smEntryNilai.setVisible(true);
    smEntryMhs.setVisible(true);
    
    if (levelUser.equals("petugas")) {
        mnUser.setVisible(false);
    }
    if (levelUser.equals("mahasiswa")) {
        mnUser.setVisible(false);
        smEntryNilai.setVisible(false);
        smEntryMhs.setVisible(false);
        mnJurusan.setVisible(false);
        mnMatkul.setVisible(false);
    }
    smLogin.setText("Logout");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnUtilitas = new javax.swing.JMenu();
        smLogin = new javax.swing.JMenuItem();
        smKeluar = new javax.swing.JMenuItem();
        mnNilai = new javax.swing.JMenu();
        smEntryNilai = new javax.swing.JMenuItem();
        smLapNilai = new javax.swing.JMenuItem();
        mnJurusan = new javax.swing.JMenu();
        smEntryProdi = new javax.swing.JMenuItem();
        smEntryKelas = new javax.swing.JMenuItem();
        smEntryKonsentrasi = new javax.swing.JMenuItem();
        LapKONSEN = new javax.swing.JMenuItem();
        mnMatkul = new javax.swing.JMenu();
        smEntryMatkul = new javax.swing.JMenuItem();
        mnMahasiswa = new javax.swing.JMenu();
        smEntryMhs = new javax.swing.JMenuItem();
        smLapDataMhs = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenu();
        smEditUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        mnUtilitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsg/image/Home.png"))); // NOI18N
        mnUtilitas.setText("Utilitas");

        smLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smLoginActionPerformed(evt);
            }
        });
        mnUtilitas.add(smLogin);

        smKeluar.setText("Exit Program");
        smKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smKeluarActionPerformed(evt);
            }
        });
        mnUtilitas.add(smKeluar);

        jMenuBar1.add(mnUtilitas);

        mnNilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsg/image/nilai.jpeg"))); // NOI18N
        mnNilai.setText("Nilai");

        smEntryNilai.setText("Entry Nilai");
        mnNilai.add(smEntryNilai);

        smLapNilai.setText("Laporan Data Nilai");
        mnNilai.add(smLapNilai);

        jMenuBar1.add(mnNilai);

        mnJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsg/image/jurusan.jpeg"))); // NOI18N
        mnJurusan.setText("Jurusan");

        smEntryProdi.setText("Entry Prodi");
        smEntryProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEntryProdiActionPerformed(evt);
            }
        });
        mnJurusan.add(smEntryProdi);

        smEntryKelas.setText("Entry Kelas");
        smEntryKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEntryKelasActionPerformed(evt);
            }
        });
        mnJurusan.add(smEntryKelas);

        smEntryKonsentrasi.setText("Entry Konsentrasi");
        smEntryKonsentrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEntryKonsentrasiActionPerformed(evt);
            }
        });
        mnJurusan.add(smEntryKonsentrasi);

        LapKONSEN.setText("Laporan Konsentrasi");
        LapKONSEN.setActionCommand("LapKONSEN");
        LapKONSEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapKONSENActionPerformed(evt);
            }
        });
        mnJurusan.add(LapKONSEN);

        jMenuBar1.add(mnJurusan);

        mnMatkul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsg/image/matkul.jpeg"))); // NOI18N
        mnMatkul.setText("Mata Kuliah");

        smEntryMatkul.setText("Entry Mata Kuliah");
        smEntryMatkul.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                smEntryMatkulAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        smEntryMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEntryMatkulActionPerformed(evt);
            }
        });
        mnMatkul.add(smEntryMatkul);

        jMenuBar1.add(mnMatkul);

        mnMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsg/image/mhs.jpeg"))); // NOI18N
        mnMahasiswa.setText("Mahasiswa");

        smEntryMhs.setText("Entry Data Mahasiswa");
        smEntryMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEntryMhsActionPerformed(evt);
            }
        });
        mnMahasiswa.add(smEntryMhs);

        smLapDataMhs.setText("Laporan Data Mahasiswa");
        smLapDataMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smLapDataMhsActionPerformed(evt);
            }
        });
        mnMahasiswa.add(smLapDataMhs);

        jMenuBar1.add(mnMahasiswa);

        mnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsg/image/user.jpeg"))); // NOI18N

        smEditUser.setText("Edit User");
        smEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEditUserActionPerformed(evt);
            }
        });
        mnUser.add(smEditUser);

        jMenuBar1.add(mnUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(971, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void smLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smLoginActionPerformed
        // TODO add your handling code here:
        if("Login".equals(FrameMENU.smLogin.getText())) {
            FrameLOGIN login = new FrameLOGIN();
            login.setVisible(true);
            this.setVisible(false);
        }
        else {
            FrameMENU.loginGagal();
        }
    }//GEN-LAST:event_smLoginActionPerformed

    private void smKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_smKeluarActionPerformed

    private void smEntryProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEntryProdiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FramePRODI a = new FramePRODI();
        a.setVisible(true);
    }//GEN-LAST:event_smEntryProdiActionPerformed

    private void smEntryKonsentrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEntryKonsentrasiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrameKONSEN a = new FrameKONSEN();
        a.setVisible(true);
    }//GEN-LAST:event_smEntryKonsentrasiActionPerformed

    private void smEntryMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEntryMhsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrameMHS a = new FrameMHS();
        a.setVisible(true);
    }//GEN-LAST:event_smEntryMhsActionPerformed

    private void smEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEditUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrameUSER a = new FrameUSER();
        a.setVisible(true);
    }//GEN-LAST:event_smEditUserActionPerformed

    private void smEntryKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEntryKelasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrameKELAS a = new FrameKELAS();
        a.setVisible(true);
    }//GEN-LAST:event_smEntryKelasActionPerformed

    private void smLapDataMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smLapDataMhsActionPerformed
        // TODO add your handling code here:
        FrameLapMHS a = new FrameLapMHS();
        a.setVisible(true);
    }//GEN-LAST:event_smLapDataMhsActionPerformed

    private void smEntryMatkulAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_smEntryMatkulAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_smEntryMatkulAncestorAdded

    private void smEntryMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEntryMatkulActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrameMATKUL a = new FrameMATKUL();
        a.setVisible(true);
    }//GEN-LAST:event_smEntryMatkulActionPerformed

    private void LapKONSENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapKONSENActionPerformed
        // TODO add your handling code here:
        FrameLapKONSEN a = new FrameLapKONSEN();
        a.setVisible(true);
    }//GEN-LAST:event_LapKONSENActionPerformed
                                                                                                             
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LapKONSEN;
    private javax.swing.JMenuBar jMenuBar1;
    private static javax.swing.JMenu mnJurusan;
    private static javax.swing.JMenu mnMahasiswa;
    private static javax.swing.JMenu mnMatkul;
    private static javax.swing.JMenu mnNilai;
    private static javax.swing.JMenu mnUser;
    private javax.swing.JMenu mnUtilitas;
    private javax.swing.JMenuItem smEditUser;
    private javax.swing.JMenuItem smEntryKelas;
    private javax.swing.JMenuItem smEntryKonsentrasi;
    private javax.swing.JMenuItem smEntryMatkul;
    private static javax.swing.JMenuItem smEntryMhs;
    private static javax.swing.JMenuItem smEntryNilai;
    private javax.swing.JMenuItem smEntryProdi;
    private javax.swing.JMenuItem smKeluar;
    private javax.swing.JMenuItem smLapDataMhs;
    private javax.swing.JMenuItem smLapNilai;
    private static javax.swing.JMenuItem smLogin;
    // End of variables declaration//GEN-END:variables
}
